### ISSUE TITLE
F-32 En formulario de organización al agregar contacto no guarda sexo, cargo ni correo.

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/si_iap#32]

**Comment by pmartinez5** [comment]
[
![FireShot Capture 082 - MIVIAP 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/139568010-65a8d00a-cf28-43b4-9784-6dbdbdc9b4c0.png)
](url)

**Comment by pmartinez5** [comment]
PU- F-32 En formulario de organización al agregar contacto no guarda sexo, cargo ni correo
