### ISSUE TITLE
R-38 En formulario de organización acompañada y de organización no acompañada que al elegir municipios donde opera, ponga automaticamente como región la del primer municipio.

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/si_iap#38]

**Comment by pmartinez5** [comment]
[
![FireShot Capture 068 - MIVIAP 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/139520719-5f1f1bae-9170-4e63-8d71-fdcf0c77debf.png)
](url)
P-U-R-38 En formulario de organización acompañada y de organización no acompañada que al elegir municipios donde opera, ponga automaticamente como región la del primer municipio

**Comment by pmartinez5** [comment]
[
![FireShot Capture 070 - MIVIAP 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/139520828-85ffeb72-d4b8-4e0e-a32a-7f8c65dfac53.png)
](url)
