### ISSUE TITLE
R-39 Que en listado de organización una columna sea región, también en resumen que aparezca región [2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/si_iap#39]

**Comment by pmartinez5** [comment]
[
![FireShot Capture 072 - MIVIAP 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/139520954-986d047b-1ea1-491e-b0cf-a3137dac9a6b.png)
](url)

R-39 Que en listado de organización una columna sea región, también en resumen que aparezca región

**Comment by pmartinez5** [comment]
[
![FireShot Capture 073 - MIVIAP 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/139520997-84a294b5-5c8a-45df-9e4f-df38e6a4a3d8.png)
](url)
