### ISSUE TITLE
R-40 Que en todos los tipos de organización se pueda especificar municipo [0,6]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/si_iap#40]

**Comment by pmartinez5** [comment]
[
![FireShot Capture 074 - MIVIAP 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/139556221-373a697c-6566-4514-aa99-9c21cf9fcf73.png)

P-U R-40 Que en todos los tipos de organización se pueda especificar municipo

**Comment by pmartinez5** [comment]
[
![FireShot Capture 075 - MIVIAP 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/139556277-d5fa01e9-4406-4403-8722-781f5de94be1.png)
](url)

**Comment by pmartinez5** [comment]
[
![FireShot Capture 076 - MIVIAP 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/139556301-52ffd2ac-b16f-48e4-b140-f0277c0c382f.png)
](url)

**Comment by pmartinez5** [comment]
[
![FireShot Capture 077 - MIVIAP 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/139556358-d05c3fc5-1426-4836-b67b-6a763ca365c9.png)
](url)

**Comment by pmartinez5** [comment]
![FireShot Capture 078 - MIVIAP 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/139556394-d6a8e805-c35e-4d8d-8937-d417ea39685c.png)
