### ISSUE TITLE
F-2 En formulario organización, en el listado de contactos, no está permitiendo buscar entre las personas registradas en el sistema (en lo posible arreglar en sip) [1]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/si_iap#7]

**Comment by alejocruzrcc** [comment]
Al hacer cambios en sipo no se daña sivel2_gen:
![Captura de pantalla de 2021-06-19 10-04-45](https://user-images.githubusercontent.com/12545631/122646660-e865b580-d0e5-11eb-8cd2-3d5b89921228.png)
![Captura de pantalla de 2021-06-19 10-04-54](https://user-images.githubusercontent.com/12545631/122646663-eac80f80-d0e5-11eb-9898-03e24ae79d63.png)

**Comment by alejocruzrcc** [comment]
Prueba de funcionamiento, Autocompleta persona y tambien contactos de organizaciones sociales existentes.

https://user-images.githubusercontent.com/12545631/122647077-0d5b2800-d0e8-11eb-8589-0ef5ab889d6b.mp4

**Comment by vtamara** [comment]
En primer caso de prueba, si  permitió autocompletar con un contacto existente, se cambio el sexo --esperando que modificar el registro persona subyacente--, pero generó el errro siguiente:
![screencapture-nodos-pasosdejesus-org-3000-iap-si-orgsociales-2021-06-19-12_48_07](https://user-images.githubusercontent.com/701221/122651201-e9561180-d0fc-11eb-8313-ac15942bfd88.png)
